# Generated by Django 5.1.7 on 2025-06-25 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='store_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('food', 'jedzenie'), ('cats', 'koty'), ('travels', 'podróże'), ('furniture', 'meble'), ('fees', 'opłaty'), ('health', 'zdrowie'), ('entertaiment', 'rozrywka'), ('others', 'inne')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
