# Generated by Django 5.1.7 on 2025-06-30 09:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_store_date_receipt_date_groceryitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Miejsce zakupy')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data zakupu')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa produktu/usługi')),
                ('category', models.CharField(choices=[('food', 'jedzenie'), ('cats', 'koty'), ('travels', 'podróże'), ('fees', 'opłaty'), ('health', 'zdrowie'), ('entertaiment', 'rozrywka'), ('others', 'inne')], max_length=100, verbose_name='Kategoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='grocery_item',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=6, null=True, verbose_name='Waga')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cena jednostkowa/kg')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.expense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.product')),
            ],
        ),
        migrations.DeleteModel(
            name='GroceryItem',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
