# Generated by Django 5.1.7 on 2025-07-03 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_expense_product_remove_receiptitem_grocery_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena jednostkowa/kg'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Waga'),
        ),
    ]
