# Generated by Django 5.1.7 on 2025-07-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_expenseitem_price_alter_expenseitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
    ]
